version: "3.9"

services:
  duckdns:
    build: ./duckdns
    container_name: duckdns-updater
    restart: always
    environment:
      - DOMAIN=${DUCKDNS_DOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}

  backend:
    build: ./backend
    container_name: telemetry-backend
    ports:        # 外部公開 → 内部
      - "8000:8000"
    volumes:      # 開発中ホットリロードしたい場合
      - ./backend/app:/app/app
      - ./backend/telemetry.db:/app/telemetry.db
    networks:
      - telemetry-net

  frontend:
    container_name: "telemetry-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

networks:
  telemetry-net:
    driver: bridge
